language: python
sudo: false
cache: pip
python:
 - "2.7"
install:
 - "uname -a"
 - "lsb_release -a"
 - "couchdb -V"
 - "curl http://127.0.0.1:5984/"
 - "redis-cli ping"
 - "psql -c 'create database pillowtop' -U postgres"
 - "pip install -e . --process-dependency-links"
 - "pip install coverage coveralls"
before_script:
  - "sleep 10"
  - "curl http://localhost:9200/"  # print ES info
script: coverage run manage.py test
after_success:
 - coveralls
services:
  - postgresql
  - couchdb
  - redis-server
  - elasticsearch
